name: Create Empty Branch

on:
  workflow_dispatch: # Menjalankan workflow secara manual

jobs:
  create-empty-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Create an empty branch
        run: |
          git fetch origin
          git checkout --orphan new-empty-branch # Ganti dengan nama branch baru
          git reset --hard                       # Hapus semua file dan commit yang mungkin ada
          git clean -fdx                         # Pastikan direktori kerja benar-benar bersih
          git commit --allow-empty -m "Initial empty commit" # Commit kosong
          git push origin new-empty-branch       # Push branch ke repository