name: Unpack File with Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      zip_file:
        description: 'Nama file zip yang akan diekstrak'
        required: true
        default: '.zip'
      extract_to:
        description: 'Tujuan direktori ekstrak'
        required: true
        default: ''
      commit_message:
        description: 'Pesan komit khusus (opsional)'
        required: false
        default: 'Add extracted files'

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip (if needed)
        run: sudo apt-get install unzip -y

      - name: Unpack specified zip file to target directory
        run: unzip -o ${{ github.event.inputs.zip_file }} -d ${{ github.event.inputs.extract_to }}

      - name: List extracted files for verification
        run: ls -R ${{ github.event.inputs.extract_to }}

      - name: Remove zip file after extraction
        run: rm -f ${{ github.event.inputs.zip_file }}

      - name: Confirm zip file removal
        run: |
          if [ -f "${{ github.event.inputs.zip_file }}" ]; then
            echo "Error: ZIP file was not deleted"
            exit 1
          else
            echo "ZIP file successfully deleted"
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push