name: Mirror to Codeberg

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 */8 * * *"  # Setiap 8 jam

jobs:
  generate_ssh_key_and_mirror:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode dari repositori GitHub
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Generate SSH Key Pair
    - name: Generate SSH Key Pair
      run: |
        # Membuat direktori untuk kunci SSH dan menghasilkan pasangan kunci baru
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f ~/.ssh/id_rsa -N ""
        echo "SSH key pair generated"

    # Menampilkan kunci publik di log (manual step untuk menambahkan kunci ke Codeberg)
    - name: Show SSH Public Key
      run: |
        # Menampilkan kunci publik untuk ditambahkan ke Codeberg
        cat ~/.ssh/id_rsa.pub
        echo "The public key above must be added to your Codeberg account."

    # Menambahkan kunci privat ke GitHub Secrets (manual step)
    - name: Set up SSH for GitHub Actions
      run: |
        # Menyimpan kunci privat dari Secrets GitHub
        echo "${{ secrets.CODEBERG_SSH }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Menambahkan host Codeberg ke known_hosts untuk menghindari peringatan SSH
        ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
        echo "SSH setup complete"

    # Melakukan push mirror dari GitHub ke Codeberg
    - name: Mirror GitHub repo to Codeberg
      run: |
        # Mengatur remote URL ke Codeberg
        git remote set-url origin git@codeberg.org:paanci/ext.git
        # Melakukan push mirror ke Codeberg
        git push --mirror